# Generated by Django 4.0.2 on 2022-03-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('confirmpassword', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=20)),
            ],
        ),
    ]
