# Generated by Django 4.0.2 on 2022-03-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopify', '0002_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='mypassword',
        ),
    ]
