# Generated by Django 4.0.2 on 2022-03-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopify', '0003_rename_password_login_mypassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='mypassword',
            new_name='password',
        ),
    ]
