# Generated by Django 4.0.2 on 2022-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopify', '0005_rename_login_mylogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
