# Generated by Django 4.0.2 on 2022-03-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopify', '0008_rename_password_mylogin_mypassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylogin',
            old_name='mypassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='mylogin',
            old_name='myusername',
            new_name='username',
        ),
    ]
