# Generated by Django 4.0.2 on 2022-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopify', '0010_editprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriberemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
