# Generated by Django 4.0.2 on 2022-03-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopify', '0011_subscriberemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriberemail',
            old_name='email',
            new_name='subscriber_mail_ids',
        ),
    ]
