# Generated by Django 4.0.2 on 2022-03-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopify', '0013_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='', upload_to='products')),
                ('price', models.FloatField()),
                ('address', models.CharField(max_length=200)),
                ('mobileno', models.IntegerField(default='0091')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopify.category')),
            ],
        ),
    ]
