# Generated by Django 4.0.2 on 2022-03-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopify', '0020_category_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mobileno',
            field=models.IntegerField(),
        ),
    ]
